# Generated by Django 5.1.4 on 2024-12-29 09:13

import django.core.validators
import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('psw', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_number', models.IntegerField()),
                ('profile_type', models.CharField(default='guest', max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('doors_is_active', models.BooleanField(default=False)),
                ('require_document_photo', models.BooleanField(default=True)),
                ('require_registration_form', models.BooleanField(default=True)),
                ('require_billing_info', models.BooleanField(default=True)),
                ('got_document_photo', models.BooleanField(default=False)),
                ('got_billing_info', models.BooleanField(default=False)),
                ('got_registration_form', models.BooleanField(default=False)),
                ('sent_to_alloggiati_web', models.BooleanField(default=False)),
                ('sent_to_regional_tourism', models.BooleanField(default=False)),
                ('invoiced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='apartments.apartment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='apartments.room')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('individual', 'Persona Fisica'), ('company', 'Azienda')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('checkin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='users.checkinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('identity card', 'Identity Card')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document_photo', models.ImageField(blank=True, null=True, upload_to=users.utils.PathAndRename('document_photos/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'pdf'])])),
                ('document_photo_back', models.ImageField(blank=True, null=True, upload_to=users.utils.PathAndRename('document_photos/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'pdf'])])),
                ('checkin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_details', to='users.checkinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_type', models.CharField(default='owner', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkinprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='users.profile'),
        ),
    ]
