# Generated by Django 5.1.3 on 2024-11-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_rename_door_room_doors'),
        ('users', '0003_alter_checkinprofile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='apartments.room'),
        ),
    ]
