# Generated by Django 5.1.3 on 2024-11-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_checkinprofile_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinprofile',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
