# Generated by Django 5.1.3 on 2024-12-19 21:51

import django.core.validators
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_checkinprofile_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='document_photo_back',
            field=models.FileField(blank=True, null=True, upload_to=users.utils.PathAndRename('document_photos/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'pdf'])]),
        ),
    ]
