# Generated by Django 5.1.3 on 2024-12-25 08:56

import django.core.validators
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_guest_document_photo_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='document_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.PathAndRename('document_photos/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.PathAndRename('document_photos/'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'gif', 'pdf'])]),
        ),
    ]
