# Generated by Django 5.1.4 on 2024-12-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('server_uri', models.URLField(blank=True, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('info', models.TextField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('parking_info', 'Parking Information'), ('restaurants', 'Restaurants'), ('nearby', 'Nearby'), ('places_to_visit', 'Places to Visit'), ('apartment_info', 'Apartment Information'), ('room_info', 'Room Information')], default='general', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('priority', models.IntegerField(default=1)),
                ('id_device', models.CharField(blank=True, max_length=255, null=True)),
                ('check_position_code', models.CharField(blank=True, max_length=10, null=True)),
                ('access_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('access_type', models.CharField(choices=[('shelly', 'Shelly'), ('codice', 'Codice'), ('solo istruzioni', 'Solo Istruzioni')], default='solo istruzioni', max_length=20)),
                ('channel_device', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
