# Generated by Django 5.1.4 on 2024-12-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='users.profile'),
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='users.profile'),
        ),
        migrations.AddField(
            model_name='door',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='door',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='users.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='room',
            name='doors',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='apartments.door'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.profile'),
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.room'),
        ),
    ]
