# Generated by Django 5.1.3 on 2024-11-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='users.profile'),
        ),
        migrations.AddField(
            model_name='door',
            name='apartments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='door',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='users.profile'),
        ),
        migrations.AddField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.profile'),
        ),
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ManyToManyField(related_name='doors', to='apartments.room'),
        ),
    ]
