# Generated by Django 5.1.3 on 2024-11-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='apartments',
            new_name='apartment',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='room',
            new_name='rooms',
        ),
    ]
