# Generated by Django 5.1.3 on 2024-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_rename_apartments_door_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='doors', to='apartments.room'),
        ),
    ]
