# Generated by Django 5.1.4 on 2025-01-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_shelly'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
