# Generated by Django 5.1.4 on 2025-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='get_billing_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='get_document_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='get_guest_info',
            field=models.BooleanField(default=False),
        ),
    ]
