# Generated by Django 5.1.3 on 2024-11-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_remove_door_rooms_remove_room_capacity_room_door'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='door',
            new_name='doors',
        ),
    ]
