# Generated by Django 5.1.3 on 2024-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_rename_door_room_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='access_type',
            field=models.CharField(choices=[('shelly', 'Shelly'), ('codice', 'Codice'), ('solo istruzioni', 'Solo Istruzioni')], default='solo istruzioni', max_length=20),
        ),
    ]
