# Generated by Django 5.1.3 on 2024-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_door_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
