# Generated by Django 5.1.3 on 2024-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_door_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='id_device',
            field=models.CharField(max_length=255),
        ),
    ]
