# Generated by Django 5.1.3 on 2024-12-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_door_id_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='channel_device',
            field=models.IntegerField(default=0),
        ),
    ]
