# Generated by Django 5.1.3 on 2024-12-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_door_channel_device'),
        ('users', '0006_checkinprofile_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('info', models.TextField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('parking_info', 'Parking Information'), ('restaurants', 'Restaurants'), ('nearby', 'Nearby'), ('places_to_visit', 'Places to Visit'), ('apartment_info', 'Apartment Information'), ('room_info', 'Room Information')], default='general', max_length=20)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.apartment')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='users.profile')),
            ],
        ),
    ]
