# Generated by Django 5.1.3 on 2024-12-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0011_apartmentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='apartmentinfo',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.room'),
        ),
    ]
