# Generated by Django 5.1.3 on 2024-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_alter_apartmentinfo_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='room',
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='apartments',
            field=models.ManyToManyField(blank=True, related_name='apartment_info', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='apartment_info', to='apartments.room'),
        ),
    ]
