# Generated by Django 5.1.3 on 2024-12-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_remove_apartmentinfo_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='apartments',
        ),
        migrations.RemoveField(
            model_name='apartmentinfo',
            name='rooms',
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='apartment',
            field=models.ForeignKey(blank=True, default=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='apartmentinfo',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_info', to='apartments.room'),
        ),
    ]
