# Generated by Django 5.1.3 on 2024-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_alter_apartmentinfo_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='check_position_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='id_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
