# Generated by Django 5.1.3 on 2024-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_alter_door_check_position_code_alter_door_id_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='auth_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='server_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
