# Generated by Django 5.1.3 on 2024-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_alter_apartment_auth_key_alter_apartment_server_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
